# azure-pipelines-ci.yml
trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  dockerImageName: 'motoconnect-api'
  dockerRegistryServiceConnection: 'ACR-Connection'
  imageRepository: 'motoconnect-api'
  containerRegistry: 'acrMotoConnect$(Build.BuildId).azurecr.io'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: BuildJob
    displayName: 'Build Application'
    steps:
    
    # Checkout do código
    - checkout: self
      displayName: 'Checkout Repository'
    
    # Setup .NET
    - task: UseDotNet@2
      displayName: 'Use .NET 8.0'
      inputs:
        version: '8.0.x'
    
    # Restaurar dependências usando script
    - script: |
        echo "Procurando arquivos .csproj..."
        find . -name "*.csproj"
        echo "Restaurando dependências..."
        dotnet restore
      displayName: 'Restore NuGet Packages'
      workingDirectory: '$(Build.SourcesDirectory)'
    
    # Build da aplicação usando script
    - script: |
        dotnet build --configuration $(buildConfiguration) --no-restore
      displayName: 'Build Solution'
      workingDirectory: '$(Build.SourcesDirectory)'
    
    # Executar testes (se existir pasta tests)
    - task: DotNetCoreCLI@2
      displayName: 'Run Unit Tests'
      inputs:
        command: 'test'
        projects: 'tests/**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build --logger trx --collect:"XPlat Code Coverage"'
      continueOnError: true  # Continua mesmo se não houver testes
    
    # Publicar resultados dos testes
    - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()
      inputs:
        testRunner: 'VSTest'
        testResultsFiles: '**/*.trx'
        failTaskOnFailedTests: false
      continueOnError: true
    
    # Publicar aplicação
    - task: DotNetCoreCLI@2
      displayName: 'Publish Application'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'src/Api/Api.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/app --no-build'
        zipAfterPublish: false
    
    # Build da imagem Docker
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(Build.BuildId)
          latest
        arguments: '--build-arg BUILD_CONFIGURATION=$(buildConfiguration)'
    
    # Publicar artefatos
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'